n = int(input())
countries = list(enumerate(map(int, input().split()), start=1))
half = 1 << (n - 1)
left = max(countries[:half], key=lambda x: x[1])
right = max(countries[half:], key=lambda x: x[1])
print(min(left, right, key=lambda x: x[1])[0])
